### ISSUE TITLE
Refactor parser function

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/vocabulary#5]
There are some improvements that can be made to the parser function.

**To-Dos**

- [ ] Create method for parsing (list string input)
- [ ] Create method to parse from string
- [ ] Change parse from file method to use new universal parsing method
- [ ] Regarding key validation: create a config file that will handle everything (extend code, not modify)
