### ISSUE TITLE
Create handler that can generate vocabulary from database, XML, JSON, EXCEL, or CSV 

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/vocabulary#7]
The handler should be able to generate a vocabulary from different types of databases and files.

**To-Dos**

- [ ] Generate from SQL Database (PostgreSQL, MySQL, MS Server primarily)
- [ ] Generate from CSV
- [ ] Generate from JSON
- [ ] Generate from EXCEL
- [ ] Generate from XML
